require("config.cmp")
require("config.lsp")
-- require("config.lsp-zero")
require("config.nvim-tree")
require("config.toggleterm")
require("config.luasnip")
require("config.lualine")
require("config.nvim-dap")
require("config.mason")
