-- 
-- 
-- local Terminal  = require('toggleterm.terminal').Terminal
-- local lazygit = Terminal:new({
--     cmd = "lazygit",
--     direction = "float",
--     float_opts = {
--       border = "double",
--     },
-- })
-- 
-- function _lazygit_toggle()
--   lazygit:toggle()
-- end
-- 
-- vim.api.nvim_set_keymap("n", "<leader>g", "<cmd>lua _lazygit_toggle()<CR>", {noremap = true, silent = true})
-- vim.keymap.set("n", "<leader>tt", ":ToggleTermSendCurrentLine<CR>")
-- 
-- 
-- 
-- require("toggleterm").setup{ }
